version: '2'
services:
  dev-env:
    build:
      context: dev-env
      dockerfile: Dockerfile
    image: magentys/imw-dev-env:latest
    # image: ruby:2.4.1
    entrypoint: bash
    working_dir: /app
    volumes:
      - .:/app
      - ~/.ssh/:/root/.ssh
